arrowParens: 'always'
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: 'auto'
endOfLine: 'lf'
# filepath: undefined
htmlWhitespaceSensitivity: 'css'
insertPragma: false
jsxSingleQuote: false
# parser: undefined
printWidth: 80
proseWrap: 'preserve'
quoteProps: 'as-needed'
# rangeStart: 0
# rangeEnd: Infinity
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
