import type { NextPage } from 'next';
import Head from 'next/head';
import LandingPage from '../components/landing-page/landing-page';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://cdn.tailwindcss.com"></script> */}
      </Head>
      <main>
        <LandingPage />
      </main>
    </>
  );
};

export default Home;
