#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

PACKAGE_LOCK_REGEX="(^pnpm-lock\.yaml)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

if [[ $PACKAGES ]]; then
  echo "📦 $PACKAGES was changed. Running pnpm install to update your dependencies..."
  pnpm install
fi

